spring.application.name=db

# MS SQL Server Database Connection 1
spring.datasource.db1.url=
databaseName=
encrypt=
spring.datasource.db1.username=
spring.datasource.db1.password=
spring.datasource.db1.driver-class-name=

# MS SQL Server Database Connection 2
spring.datasource.db2.url=
databaseName=
encrypt=
spring.datasource.db2.username=
spring.datasource.db2.password=
spring.datasource.db2.driver-class-name=

# Hibernate Configuration for MS SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
